### ISSUE TITLE
Remove JavaScript Libraries

### ISSUE THREAD

**Issue by MasterOfTheTiger** [MasterOfTheTiger/apod-extension#14]
It would be best to remove JavaScript libraries, because it would make more concise. It might be near impossible to remove JQuery, because of the request for the API (it might be too difficult to request otherwise). If someone makes a pull request that includes the APOD API request without JQuery I can do the rest.
- [x] Replace moment.js 
- [x] Replace JQuery

**Comment by teevik** [comment]
I can try the jquery thing as well, if that's ok

**Comment by MasterOfTheTiger** [comment]
Wow! Thank you very much.

**Comment by MasterOfTheTiger** [comment]
Hey @teevik, for some reason the new date code does not work in Electron. In fact, when the code exists in the program, the entire file does not run. 
When I remove this code the script will run:

    var dateString = [
        date.toLocaleDateString("en-US", { ...localeOptions, year: "numeric" }),
        date.toLocaleDateString("en-US", { ...localeOptions, month: "2-digit" }),
        date.toLocaleDateString("en-US", { ...localeOptions, day: "2-digit" })
    ].join("-");

**Comment by teevik** [comment]
Ah hey, looks like it was an issue with electron not supporting es6 spread operator, could just do something like this instead
```javascript
var dateString = [
  date.toLocaleDateString("en-US", Object.assign({}, localeOptions, { year: "numeric" })),
  date.toLocaleDateString("en-US", Object.assign({}, localeOptions, { month: "2-digit" })),
  date.toLocaleDateString("en-US", Object.assign({}, localeOptions, { day: "2-digit" }))
].join("-");
```

**Comment by MasterOfTheTiger** [comment]
Okay! Thanks, I will try this. I am just experimenting with Electron, and I decided it would be cool to make an APOD program for it.
